version: "3.8"

# Compose file to run Arabic website with MySQL database
services:
  web:
    image: my-image
    container_name: arabic-website
    user: "node" # تشغيل كمستخدم غير جذر لتقليل المخاطر
    read_only: true # جعل نظام الملفات للقراءة فقط
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: always
    ports:
      - "8080:8000" # external:internal
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    # NOTE: Static site served by 'serve' in the image

  mysql:
    image: mysql:8
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
